### ISSUE TITLE
Cannot use souliss gateway on external network

### ISSUE THREAD

**Issue by lucacalcaterra** [souliss/bindingopenhab2#9]
The binding is structured to works only if gateway is on lan.
In this way cannot use openhab on an external server (like a VPS).

it would be useful to implement the possibility of using an external gateway

a reminder for the future for @fazioa 
thanks,
Luca

**Comment by lucacalcaterra** [comment]
ps. I found a (quite simple) way to bypass it. Create a fake ip (the same on internal lan) on remote VPS  and forward the UDP port to remote souliss gateway

**Comment by plinioseniore** [comment]
You need a VPN between your external openHAB server and the local network of your Souliss gateway.

By design Souliss doesn't include any cloud service and will never include one, so that your network will always work without any external dependency.

You can integrate other clouds as openHAB but you always need to have the gateway of your cloud on the same local network (or virtual using a VPN) of the Souliss gateway.

**Comment by lucacalcaterra** [comment]
@plinioseniore Dario , i know that i can use a VPN and Souliss require a LAN. But... forwarding the UDP port form WAN to LAN and creating a fake ip on the remote network (as my previous post) did the trick :-)
